import os
DEBUG = False
ACCESS_TOKEN = "" #FB ACCESS TOKEN
GROUPS = {
	#GROUP ID DICT ("GROUPNAME":"GROUPID")
}
MONGO_HOST = "" #MONGODB HOST NAME
MONGO_PORT =  #MONGODB PORT NUMBER
MONGO_DBNAME = "" #MONGODB DATABASE NAME
MONGO_USERNAME = "" #MONGODB USERNAME
MONGO_PASSWORD = "" #MONGODB USER PASSWORD
