import os
DEBUG = False
ACCESS_TOKEN = '626851570705028|SYdCEOUwio7LuAOvN_oKRk7SuvI'
GROUPS = {
		"engfordev":'157076174344216'
}
#MONGO_HOST = os.environ['OPENSHIFT_MONGODB_DB_HOST']
#MONGO_PORT = os.environ['OPENSHIFT_MONGODB_DB_PORT']
#MONGO_DBNAME = 'engfordev'
#MONGO_USERNAME = "admin"
#MONGO_PASSWORD = "8rNAeGHx_LTx"

MONGO_HOST = "localhost"
MONGO_PORT = 27017
MONGO_DBNAME = 'engfordev'
